baseurl = "https://kua.io"
title = "kua.io"
PygmentsCodeFences = true
canonifyurls = true
disableHugoGeneratorInject = true
enableRobotsTXT = true

[permalinks]
  posts = "/:section/:year/:month/:day/:slug/"
  talks = "/:section/:year/:month/:day/:slug/"
  projects = "/:section/:year/:month/:day/:slug/"

[params]
  author = "David Kua"
  email = "david@kua.io"
  socialLinks = true
  github = "dkua"
  frontPageMax = 10

[blackfriday]
  hrefTargetBlank = true
